# Dependencies
highlighter:      rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed

# Permalinks
permalink:        /:title/

# Setup
title:            R#
host:		  0.0.0.0
tagline:          'import coffee'
description:      'penchant for python'
url:              https://www.rachsharp.co.uk
baseurl:          /

author:
  name:           'Rachel Sharp'
  url:            https://www.rachsharp.co.uk/author
  email:	  me@rachsharp.co.uk

excerpt_separator: <!--more-->

paginate:         5
paginate_path: "/page/:num/"

# Custom vars
#version:          2.1.0
enabled_reading_lists: [webmethods, python]

github:
  repo:           https://github.com/poole/hyde

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
